### Abstract Vector Spaces

#### Problem 1

#### Problem 2

#### Problem 3

### Gram Schmidt Orthogonalization

Khan academy video: https://www.youtube.com/watch?v=rHonltF77zI

In [1]:
import numpy as np
import math

In [2]:
def magnitude(u):
    '''
    Find the magnitude of the vector
    '''
    return math.sqrt(u@u)

In [3]:
def projection(u, v):
    '''
    Get the projection of u onto v
    '''
    mag_v = magnitude(v)
    projection = (u@v)*v/mag_v**2
    return projection

In [5]:
def projection_unit(u, v):
    '''
    Get the projection of u onto v given that v is a unit vector
    '''
    projection = (u@v)*v
    return projection

In [4]:
def normalize_vector(u):
    '''
    Convert vector to unit vector
    '''
    mag_u = magnitude(u)
    return u / mag_u

#### Problem 1

In [64]:
v1 = np.array([4, 2])
v2 = np.array([1, 3])

In [65]:
e1 = normalize_vector(v1)

In [66]:
# projection of v2 onto e1
proj_v2 = projection_unit(v2, e1)

In [67]:
perp_proj_v2 = v2 - proj_v2

In [68]:
e2 = normalize_vector(perp_proj_v2)

In [69]:
# answer
e1, e2

(array([0.89442719, 0.4472136 ]), array([-0.4472136 ,  0.89442719]))

In [70]:
# we can also verify that e1.e2 = 0 and e1.e1 = 1
np.round(e1@e2)

0.0

In [71]:
np.round(e1@e1)

1.0

#### Problem 2

In [74]:
v1 = np.array([1, 1, 0])
v2 = np.array([1, 0, 1])
v3 = np.array([0, 1, 1])

In [75]:
e1 = normalize_vector(v1)

In [77]:
proj_v2_e1 = projection_unit(v2, e1)

In [78]:
e2 = normalize_vector(v2 - proj_v2_e1)

In [79]:
proj_v3_e1 = projection_unit(v3, e1)
proj_v3_e2 = projection_unit(v3, e2)

In [80]:
e3 = normalize_vector(v3 - proj_v3_e1 - proj_v3_e2)

In [82]:
# answer
e1, e2 , e3

(array([0.70710678, 0.70710678, 0.        ]),
 array([ 0.40824829, -0.40824829,  0.81649658]),
 array([-0.57735027,  0.57735027,  0.57735027]))

In [84]:
# verification
print(np.round(e1@e2))
print(np.round(e2@e3))
print(np.round(e1@e3))

0.0
-0.0
0.0


In [85]:
print(np.round(e1@e1))
print(np.round(e2@e2))
print(np.round(e3@e3))

1.0
1.0
1.0
