In [1]:
import numpy as np
import math

### Lines

##### Problem 1

In [ ]:
# direction vector can be caliculated as v = q - p
p = np.array([1, 1, 1])
q = np.array([2, 3, 4])
v = q-p
v

### Planes

##### Problem 2

In [ ]:
p = np.array([1, 0, 0])
q = np.array([0, 1, 0])
r = np.array([0, 0, 1])

In [ ]:
v = q - p
w = r - q
v, w

In [ ]:
# calculating normal
n = np.cross(v, w)

In [ ]:
n

In [ ]:
D = n@p
D

## Projections

### Projection onto a line

In [31]:
def projection(u, v):
    '''
    The projection of u onto v given by formula (u.v)*v/|v|**2
    '''
    mag_v = math.sqrt(v@v)
    projection = (u@v)*v/math.pow(mag_v, 2)
    return projection 

##### Problem 1

In [12]:
u = np.array([4, 5, 6])
v = np.array([1, 2, 3])

In [14]:
projection_l = projection(u, v)
projection_l

array([2.28571429, 4.57142857, 6.85714286])

In [18]:
projection_l_perp = u - projection_l

In [19]:
projection_l_perp

array([ 1.71428571,  0.42857143, -0.85714286])

In [21]:
np.round(projection_l_perp @ projection_l)

0.0

Perfect!

### Projection onto a plane

##### Problem 2

In [22]:
n = np.array([1, 1, 1])
u = np.array([4, 5, 6])

In [27]:
projection_onto_n = np.round(projection(u, n))

In [28]:
projection_onto_p = np.round(u - projection_onto_n)

In [29]:
projection_onto_n, projection_onto_p

(array([5., 5., 5.]), array([-1.,  0.,  1.]))

In [30]:
np.round(projection_onto_p @ n)

0.0

### Distances

 #### Distance of a line from origin

In [43]:
def distance_from_origin_line(p0, v):
    '''
    calculate distance from origin to line l defined as p0 + tv
    '''
    projection_p = projection(p0, v)
    projection_p_perpendicular = p0 - projection_p
    mag_proj_p_perp = math.sqrt(projection_p_perpendicular@projection_p_perpendicular)
    return abs(mag_proj_p_perp)

##### Problem 3

In [33]:
p0 = np.array([4, 5, 6])
v = np.array([1, 0, 1])
distance_from_origin_line(p0, v)

5.196152422706632

 #### Distance of a plane from origin

In [40]:
def distance_from_origin_plane(p0, n):
    '''
    calculate distance from origin to plane p defined as n.[(x, y, z) - p0] = 0
    '''
    mag_n = math.sqrt(n@n)
    return abs(p0@n/mag_n)

##### Problem 4

In [41]:
n = np.array([-3, 0, -4])
p0 = np.array([1, 2, 3])

In [42]:
distance_from_origin_plane(p0, n)

3.0

## Basis

### Generic Basis

### Orthonormal Basis

#### Problem 1

## Distilling Basis

In [1]:
from sympy.matrices import Matrix

#### Problem 1 

In [2]:
A = Matrix([[4, -4, 0],
 [1, 1, -2],
 [2, -6, 4]])

In [3]:
matrix, _ = A.rref()

In [4]:
matrix

Matrix([
[1, 0, -1],
[0, 1, -1],
[0, 0,  0]])

##### Row Space

##### Column Space

In [5]:
A.columnspace()

[Matrix([
 [4],
 [1],
 [2]]),
 Matrix([
 [-4],
 [ 1],
 [-6]])]

Perfect

##### Null Space

In [7]:
A.nullspace()

[Matrix([
 [1],
 [1],
 [1]])]

Perfect

#### Problem 2

In [8]:
A = Matrix([[1, 3, 1, 4],
     [2, 7, 3, 9],
     [1, 5, 3, 1],
     [1, 2, 0, 8]])

In [10]:
matrix, _ = A.rref()

In [11]:
matrix

Matrix([
[1, 0, -2, 0],
[0, 1,  1, 0],
[0, 0,  0, 1],
[0, 0,  0, 0]])

##### Row Space

##### Column Space

In [12]:
A.columnspace()

[Matrix([
 [1],
 [2],
 [1],
 [1]]),
 Matrix([
 [3],
 [7],
 [5],
 [2]]),
 Matrix([
 [4],
 [9],
 [1],
 [8]])]

perfect

##### Null Space

In [13]:
A.nullspace()

[Matrix([
 [ 2],
 [-1],
 [ 1],
 [ 0]])]

perfect