### Reference:
https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/

In [1]:
import numpy as np
import scipy.linalg as la

### Matrix Operations

In [15]:
M = np.array([[3,4],[-1,5]])
N = np.array([[5,7],[-9,6], [2, 3]])
L = np.array([[1], [2]])
print(M)
print("------")
print(N)
print("------")
print(L)

[[ 3  4]
 [-1  5]]
------
[[ 5  7]
 [-9  6]
 [ 2  3]]
------
[[1]
 [2]]


##### Normal Multiplication

In [5]:
# multiplies corresponding elements
M * M

array([[ 9, 16],
       [ 1, 25]])

##### Matrix Multiplication

In [13]:
M@M

array([[ 5, 32],
       [-8, 21]])

In [14]:
M@L

array([[11],
       [ 9]])

In [16]:
# Compute 2L - 3ML
2*L - 3*(M@L)

array([[-31],
       [-23]])

##### Matrix Powers

Only defined for square matrices

In [17]:
from numpy.linalg import matrix_power as mpow

In [18]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [22]:
# mpow(M,2) is same as M@M
M@M

array([[ 5, 32],
       [-8, 21]])

##### Matrix Transpose

In [23]:
M.T

array([[ 3, -1],
       [ 4,  5]])

In [28]:
# M @ M.T is a symmetric Matrix
M @ M.T

array([[25, 17],
       [17, 26]])

##### Matrix Inverse

In [25]:
la.inv(M)

array([[ 0.26315789, -0.21052632],
       [ 0.05263158,  0.15789474]])

In [27]:
# M @ inv(M) is an identity matrix
M @ la.inv(M)

array([[1.00000000e+00, 0.00000000e+00],
       [5.55111512e-17, 1.00000000e+00]])

##### Trace

In [29]:
M

array([[ 3,  4],
       [-1,  5]])

In [31]:
# Trace is the sum of diagonals of the matrix
np.trace(M)

8

##### Determinant

In [32]:
la.det(M)

19.0

In [33]:
M

array([[ 3,  4],
       [-1,  5]])

##### Verifying the Cayley-Hamilton Theorem

In [34]:
trace_M = np.trace(M)
det_M = la.det(M)
I = np.eye(2)
M @ M - trace_M * M + det_M * I

array([[0., 0.],
       [0., 0.]])