In [2]:
import numpy as np

### Gauss-Jordan Elimination

#### Example 1

In [36]:
augmented_matrix = np.array([[1, 2, 5], [3, 9, 21]])

In [37]:
augmented_matrix

array([[ 1,  2,  5],
       [ 3,  9, 21]])

In [38]:
# get rows
print("row1: {}".format(augmented_matrix[:1]))
print("row2: {}".format(augmented_matrix[1:2]))

row1: [[1 2 5]]
row2: [[ 3  9 21]]


In [39]:
augmented_matrix[1:2] = augmented_matrix[1:2] - 3*augmented_matrix[:1]

In [40]:
augmented_matrix

array([[1, 2, 5],
       [0, 3, 6]])

In [41]:
augmented_matrix[1:2] = augmented_matrix[1:2] * (1/3)

In [42]:
augmented_matrix

array([[1, 2, 5],
       [0, 1, 2]])

In [43]:
augmented_matrix[:1] = augmented_matrix[:1] - 2 * augmented_matrix[1:2]

In [44]:
augmented_matrix

array([[1, 0, 1],
       [0, 1, 2]])

In [45]:
# we have found the solution
x1 = 1
x2 = 2

### Example 2

In [46]:
augmented_matrix = np.array([[1, 2, 3, 14], [2, 5, 6, 30], [-1, 2, 3, 12]])

In [47]:
augmented_matrix

array([[ 1,  2,  3, 14],
       [ 2,  5,  6, 30],
       [-1,  2,  3, 12]])

In [48]:
# get rows
print("row1: {}".format(augmented_matrix[:1]))
print("row2: {}".format(augmented_matrix[1:2]))
print("row3: {}".format(augmented_matrix[2:3]))

row1: [[ 1  2  3 14]]
row2: [[ 2  5  6 30]]
row3: [[-1  2  3 12]]


##### Forward Phase

We move from left to right

In [49]:
augmented_matrix[1:2] = augmented_matrix[1:2] - 2 * augmented_matrix[:1]
augmented_matrix[2:3] = augmented_matrix[2:3] + augmented_matrix[:1]

In [50]:
augmented_matrix

array([[ 1,  2,  3, 14],
       [ 0,  1,  0,  2],
       [ 0,  4,  6, 26]])

In [51]:
augmented_matrix[2:3] = augmented_matrix[2:3] - 4*augmented_matrix[1:2]

In [52]:
augmented_matrix

array([[ 1,  2,  3, 14],
       [ 0,  1,  0,  2],
       [ 0,  0,  6, 18]])

In [53]:
augmented_matrix[2:3] = augmented_matrix[2:3] / 6

In [54]:
augmented_matrix

array([[ 1,  2,  3, 14],
       [ 0,  1,  0,  2],
       [ 0,  0,  1,  3]])

##### Backward Phase

Move from right to left

In [55]:
augmented_matrix[:1] = augmented_matrix[:1] - 3*augmented_matrix[2:3]

In [56]:
augmented_matrix

array([[1, 2, 0, 5],
       [0, 1, 0, 2],
       [0, 0, 1, 3]])

In [57]:
augmented_matrix[:1] = augmented_matrix[:1] - 2*augmented_matrix[1:2]

In [58]:
augmented_matrix

array([[1, 0, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 3]])

In [59]:
# we have found the solution
x = 1
y = 2
z = 3